#! /bin/sh
source ~/.profile

killall panel || true
panel &

xmodmap ~/.Xmodmap

xset r rate 300 20
xset m 1/1 4
xset dpms 0 0 0
xset s off
xset -dpms
xset s noblank
xset s noexpose
xset s 0 0
xset s noexpose
xset s noexpose
# picom & disown
# nm-applet & disown

bspc monitor -d browser editor terminal 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap           0

bspc rule -a Emacs state=tiled
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


feh --recursive --bg-fill --randomize ~/git/dots/wallpapers/ &
