#! /bin/sh
set -x

source ~/.profile

killall panel || true
panel &
whoami > /tmp/whoami
xmodmap ~/.Xmodmap || true

xset r rate 300 20
xset m 1/1 4
xset dpms 0 0 0
xset s off
xset -dpms
xset s noblank
xset s noexpose
xset s 0 0
xset s noexpose
xset s noexpose
# picom & disown
# nm-applet & disown

bspc monitor -d browser editor terminal 4 5 6 7 8 9

bspc config border_width         0

bspc config normal_border_color   "#44475a"
bspc config active_border_color   "#6272a4"
bspc config focused_border_color  "#ff79c6"

# dynamically setting the border width based on the number of tiled windows
bspc subscribe node_add node_remove desktop_focus | while read -r _; do
    DESKTOP=$(bspc query -D -d focused)
    WINDOW_COUNT=$(bspc query -N -d "$DESKTOP" -n .window | wc -l)

    if [ "$WINDOW_COUNT" -eq 1 ]; then
        bspc config border_width 0;
        bspc config window_gap 0;
    else
        bspc config border_width 2;
        bspc config window_gap 5;
    fi
done &


bspc rule -a Emacs state=tiled
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


feh --no-fehbg --bg-scale ~/git/dots/wallpapers/034.png
