#! /bin/sh

export PANEL_FIFO=/tmp/panel-fifo
export PANEL_HEIGHT=24
export PANEL_WM_NAME=bspwm_panel

if [ -z "$PANEL_FONT" ]; then
    PANEL_FONT="-*-unifont-*-*-*-*-16-*-*-*-*-*-*-*"
fi
export PANEL_FONT

function dates {
    date +'%Y.%m.%d %a ' | tr '\n' ' '
    for tz in $(cat ~/.config/tz.txt);
    do
        echo -e $tz ": "; TZ=$tz date +'%H:%M:%S'
    done | tr '\n' ' '
}

function fdates { ## Formatted dates
    echo $(dates)". . . . . . . ."
}


if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

xtitle -sf 'T%s\n' > "$PANEL_FIFO" &
echo "S"$(fdates) > "$PANEL_FIFO" &
while sleep 1; do echo "S"$(fdates); done > "$PANEL_FIFO" &
bspc subscribe report > "$PANEL_FIFO" &

. panel_colors

panel_bar < "$PANEL_FIFO" | lemonbar -b -a 32 -u 2 -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -f "$PANEL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -m -a "$PANEL_WM_NAME")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
